server:
  port: 8080

spring:
  data:
    mongodb:
      # MongoDB Local - Working 100%
      uri: mongodb+srv://dangthanhanh_db_user:01862001@cluster0.ozaixgp.mongodb.net/?appName=Cluster0
      database: wanderlust
      
      # MongoDB Atlas - SSL errors with Java 21 (tested with driver 4.11.1 and 5.2.1)
      # uri: mongodb+srv://dangthanhanh_db_user:01862001@cluster0.ozaixgp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      # database: Wanderlust
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 539952006239-0s0encdik2u3tlmho12tb67v5vttt0gn.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
            scope:
              - email
              - profile
              - openid
          facebook:
            clientId: 3049561311868177
            clientSecret: da74e30a644d9e78ee33e2e2338382d7
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            user-name-attribute: id
